# 🔖一、Pandas和Numpy基础

嗨，欢迎来到 Numpy和Pandas 的世界。

在正式开始学习前，想提醒下你：

1. 作业题在末尾。抬头看右上角蓝色 Fork 按钮，点击它，创建→使用 基础镜像 运行。
2. 用 Python3 kernel 运行。 进入 ModelWhale 编程界面后，注意右上角蓝色圆圈那里一定得是 Python 3。否则需要 Kernel - 更改Kernel类型 - Python 3。
2.如何运行单个 cell？ 鼠标单击 cell 左侧即可选中，shift + Enter 运行，cell 左侧出现数字序号即代表运行成功
3. 运行时使用基础镜像即可。这个镜像已经搭配好Python基础环境，可以满足基础使用，不用在本地配置Python环境，十分方便。如果你不小心选择了其他镜像，也没多大事，去计算环境里关闭实例，换个镜像运行即可。

好了，不啰嗦了，试试运行下方这些代码，开始探索吧。


Numpy(Numerical Python) 是 Python语言的一个第三方库，支持大量的维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库。Numpy是一个运行速度非常快的数学库，主要用于数组计算。

Pandas是基于NumPy数组构建的，也是Python语言的第三方库，Pandas使数据预处理、清洗、分析工作变得更快更简单，主要用于数据分析。

Pandas是专门为处理表格和混杂数据设计的，相当于Python的Excel，而Numpy更适合处理统一的数组数据。

Numpy和Pandas都是第三方库，需要预先安装好后才能导入使用，如果安装了Anaconda，则不必另外安装（因为Anaconda会自动安装很多数据分析用的第三方库）。

In [1]:
#导包
import pandas as pd
import numpy as np

ModuleNotFoundError: No module named 'pandas'

## 1.将下面的字典创建为DataFrame

In [6]:
data = {"grammer":['Python', 'C', 'Java', 'GO', np.NaN, 'SQL', 'PHP', 'Python'],
       "score":[1.0, 2.0, np.NaN, 4.0, 5.0, 6.0, 7.0, 10.0]}
df = pd.DataFrame(data)
df

grammer  score
0  Python    1.0
1       C    2.0
2    Java    NaN
3      GO    4.0
4     NaN    5.0
5     SQL    6.0
6     PHP    7.0
7  Python   10.0

## 2.提取含有字符串"Python"的行

In [7]:
#方法一：
df[df['grammer'] == 'Python']
#方法二：
results = df['grammer'].str.contains('Python')
results.fillna(value=False, inplace=True)
df[results]

grammer  score
0  Python    1.0
7  Python   10.0

## 3.输出df的所有列名

In [8]:
df.columns

Index(['grammer', 'score'], dtype='object')

## 4.修改第二列列名为'popularity'

In [9]:
df.rename(columns={'score':'popularity'}, inplace=True)
df

grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         NaN
3      GO         4.0
4     NaN         5.0
5     SQL         6.0
6     PHP         7.0
7  Python        10.0

## 5.统计grammer列中每种编程语言出现的次数

In [10]:
df['grammer'].value_counts()

Python    2
Java      1
GO        1
C         1
PHP       1
SQL       1
Name: grammer, dtype: int64

## 6.将空值用上下值的平均值填充

In [11]:
df['popularity'] = df['popularity'].fillna(df['popularity'].interpolate())
df

grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         3.0
3      GO         4.0
4     NaN         5.0
5     SQL         6.0
6     PHP         7.0
7  Python        10.0

## 7.提取popularity列中值大于3的行

In [12]:
df[df['popularity'] > 3]

grammer  popularity
3      GO         4.0
4     NaN         5.0
5     SQL         6.0
6     PHP         7.0
7  Python        10.0

## 8.按照grammer列进行去除重复值

In [13]:
df.drop_duplicates(['grammer'])

grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         3.0
3      GO         4.0
4     NaN         5.0
5     SQL         6.0
6     PHP         7.0

## 9.计算popularity列平均值

In [14]:
df['popularity'].mean()

4.75

## 10.将grammer列转换为list

In [15]:
df['grammer'].to_list()

['Python', 'C', 'Java', 'GO', nan, 'SQL', 'PHP', 'Python']

## 11.将DataFrame保存为CSV

In [16]:
df.to_csv('test.csv')

## 12.查看数据行列数

In [17]:
df.shape

(8, 2)

## 13.提取popularity列值大于3小于7的行

In [18]:
df[(df['popularity'] > 3) & (df['popularity'] < 7)]

grammer  popularity
3      GO         4.0
4     NaN         5.0
5     SQL         6.0

## 14.交换两列位置

In [19]:
#方法一
temp = df['popularity']
df.drop(labels=['popularity'], axis=1, inplace=True)
df.insert(0, 'popularity', temp)
df

popularity grammer
0         1.0  Python
1         2.0       C
2         3.0    Java
3         4.0      GO
4         5.0     NaN
5         6.0     SQL
6         7.0     PHP
7        10.0  Python

In [20]:
##方法2
#cols = df.columns[[1,0]]
#df = df[cols]
#df

## 15.提取popularity列最大值所在行

In [21]:
df[df['popularity'] == df['popularity'].max()]

popularity grammer
7        10.0  Python

## 16. 随机生成20个0-100的随机整数：Numpy.random.randint()

In [22]:
np.random.randint(0, 100, 20)

array([72, 68,  6, 41, 22, 63, 27, 43, 55, 26, 60, 89, 29, 83, 23, 68, 37,
       70, 42, 31])

## 17. 生成20个0-100固定步长的数：Numpy.arange()

- np.arange()函数分为一/两/三个参数三种情况：
 - 1）一个参数时，参数值为终点，起点取默认值0，步长取默认值1。
 - 2）两个参数时，第一个参数为起点，第二个参数为终点，步长取默认值1。
 - 3）三个参数时，第一个参数为起点，第二个参数为终点，第三个参数为步长。其中步长支持小数


In [23]:
np.arange(0, 100, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

## 18. 生成20个指定分布（如标准正态分布）的数：Numpy.random.normal()

In [24]:
np.random.normal(0, 1, 20)

array([-0.20191223,  0.71407157, -0.9127828 , -0.65248936,  1.06513536,
        0.31551879, -0.71842129, -0.75766808,  0.488825  , -1.15330714,
       -0.50300377, -0.4937517 , -1.11488371, -0.70628642, -1.86134249,
       -0.03509479,  0.20524998,  0.04379019,  0.39735111, -1.58616105])

## 19. 提取score列中可以整除5的数字位置：Numpy.argwhere()

In [25]:
data = {"grammer":['Python', 'C', 'Java', 'GO', 'css', 'SQL', 'PHP', 'Python'],
       "score":[1.0, 2.0, 6.0, 4.0, 5.0, 6.0, 7.0, 10.0]}
df = pd.DataFrame(data)
np.argwhere(np.array(df['score'] % 5 == 0))

array([[4],
       [7]])

## 20. 查看两列值相等的行号：Numpy.where()

- np.where()用法：
 - np.where(condition, x, y)： # 满足条件(condition)，输出x，不满足输出y。
 - np.where(condition)：只有条件 (condition)，没有x和y，则输出满足条件 (即非0) 元素的坐标 (等价于numpy.nonzero)。当条件成立时，where返回的是每个符合condition条件元素的坐标,返回的是以元组的形式。

In [26]:
df['cycle'] = [2.0, 3.0, 6.0, 3.0, 5.0, 2.0, 7.0, 5.0]
#方法一：值相等
df[df['score'] == df['cycle']].index
 
#方法二：np.where()
np.where(df.score == df.cycle)

(array([2, 4, 6]),)

## 21. 查找第一列的局部最大值位置：Numpy.sign()

In [27]:
#思路：查找比它前一个和后一个数字都大数字
tem = np.diff(np.sign(np.diff(df['score'])))
np.where(tem == -2)[0] + 1

array([2])

## 22. 对第二列计算移动平均值：Numpy.convolve()

In [28]:
np.convolve(df['cycle'], np.ones(3)/3, mode='valid')

array([3.66666667, 4.        , 4.66666667, 3.33333333, 4.66666667,
       4.66666667])

## 23. 计算两列欧式距离：Numpy.linalg.norm()

In [29]:
#方法一：公式法
import math as mt
mt.sqrt(sum((df['score']-df['cycle'])**2))
 
#方法二：numpy函数
np.linalg.norm(df['score'] - df['cycle'])

6.6332495807108

## 24. 查找某列数据中第三大值的行号：Numpy.argsort()

In [30]:
#方法一：
df['score'].argsort()[::-1][len(df)-3]
#注：argsort() -- 从小到大排, 输出索引；[[::-1]]倒序输出 -- 即为从大到小排；
 
#方法二：先进行倒序排序，然后重置索引，取第三行第一列即为第3大值的行号
df['score'].sort_values(ascending=False).reset_index().iloc[2,0]

5

## 25. numpy其他一些统计基础函数

In [31]:
np.min([1,2,3]) # 最小值
np.mean([1,2,3]) # 均值
np.median([1,2,3]) # 中位数
np.var([1,2,3]) # 方差
np.max([1,2,3]) # 最大值
np.ptp([1,2,3]) # 极差
np.std([1,2,3]) # 标准差
np.cov([1,2,3]) # 协方差
np.log1p([1,2,3]) # log(x + 1)
np.log2([1,2,3]) # 以2为底的对数
np.expm1([1,2,3]) # e的x次幂-1
np.exp([1,2,3]) # e的次数幂
np.log([1,2,3]) # 取对数
np.sqrt([1,2,3]) # 开根号
np.exp2([1,2,3]) # 平方

array([2., 4., 8.])

# ✍作业

## STEP1: 按照下列要求创建数据框

已知10位同学的学号以及语数英三科成绩如下：（都是数值型数据）

![Image Name](https://cdn.kesci.com/upload/image/r04hbyfg5c.png)

Id: [202001, 202002, 202003, 202004, 202005, 202006, 202007, 202008, 202009, 202010]
Chinese: [98, 67, 84, 88, 78, 90, 93, 75, 82, 87]
Math: [92, 80, 73, 76, 88, 78, 90, 82, 77, 69]
English: [88, 79, 90, 73, 79, 83, 81, 91, 71, 78]

要求：计算出每位同学的总成绩(SumScore)、平均成绩(MeanScore)，最高成绩(MaxScore)、最低成绩(MinScore)、最高成绩与最低成绩的极差(PtpScore)、成绩方差(VarScore)；并将所有数据保存到score数据框中；将多列数据(包括学生的ID)合并到一列中，列名设置为answer，最终只保留索引id（从0到100）和answer两列，统一保留整数；

In [43]:
import pandas as pd






表格参考👇
![Image Name](https://cdn.kesci.com/upload/image/r32awk1lnq.png?imageView2/0/w/960/h/960)



In [ ]:
df = df[['id', 'answer']]
df

In [ ]:
data = pd.concat([StudentScore.iloc[:,0],StudentScore.iloc[:,1],StudentScore.iloc[:,2],StudentScore.iloc[:,3],StudentScore.iloc[:,4],StudentScore.iloc[:,5],StudentScore.iloc[:,6],StudentScore.iloc[:,7],StudentScore.iloc[:,8],StudentScore.iloc[:,9]])
df = pd.DataFrame(data, columns=['answer'])
df['id'] = range(len(df))
df = df[['id', 'answer']]
df

## STEP2: 将结果保存为 csv 文件

In [41]:
df.to_csv('answer_1.csv', index=False, encoding='utf-8-sig')#代码自动补全的快捷键是 tab；运行完成后，左侧文件树刷新下，可以找到这份文件

## STEP3: 提交 csv 文件，获取分数结果
现在你的答案文件已经准备完毕了，怎么提交得到评分呢？

1、拷贝提交 token

去活动[提交页面](https://www.heywhale.com/home/competition/6154198bc270e400182b11f9/submit)，找到对应关卡，看到了你的 token 嘛？

拷贝到下方 cell 里（替换掉 XXXXXXX），右上角保证Kernel类型为Python3哈；

记得：每个关卡的 token 不一样。

2、找到你的答案文件路径

右侧文件树，刷新，在 project 下找到答案文件，右键点击可复制路径。

路径为 /home/mw/project/answer_1.csv，你可以再仔细查看一下哦

⚠️答案为  **100 rows × 2 columns**

![Image Name](https://cdn.kesci.com/upload/image/r4i6qf6gp7.png?imageView2/0/w/960/h/960)


In [ ]:
# 运行这个 cell 前记得一定要保证右上角 kernel为 Python 3 的噢
# 下载提交工具
!wget -nv -O heywhale_submit https://cdn.kesci.com/submit_tool/v4/heywhale_submit&&chmod +x heywhale_submit
 
# 运行提交工具
# 把下方 XXXXXXX 替换为你的 Token，submit_file 为要提交的文件名路径
# 文件名路径去左侧文件树下，刷新，找到对应的 csv 文件，右键复制路径
!./heywhale_submit -token XXXXXXX -file /home/mw/project/answer_1.csv

运行成功、显示提交完成后，即可去[提交页面](https://www.heywhale.com/home/competition/6154198bc270e400182b11f9/submit) -- 查看成绩。满分即可进入下一关。


![Image Name](https://cdn.kesci.com/upload/image/r2r21h33rz.png?imageView2/0/w/960/h/960)

没有成功也不怕，看下报错信息，对照排查下，改完重新提交咯。

祝好运 🐳